#!/bin/sh
# postinst script for modules package built from flashcache

set -e

case "$1" in
    configure)
        if [ -x /usr/sbin/update-devfsd ] ; then
            /usr/sbin/update-devfsd 2>/dev/null || true
        fi
        modprobe flashcache 2>/dev/null || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0
