Document: flashcache
Title: Debian flashcache Manual
Author: <insert document author here>
Abstract: This manual describes what flashcache is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/flashcache/flashcache.sgml.gz

Format: postscript
Files: /usr/share/doc/flashcache/flashcache.ps.gz

Format: text
Files: /usr/share/doc/flashcache/flashcache.text.gz

Format: HTML
Index: /usr/share/doc/flashcache/html/index.html
Files: /usr/share/doc/flashcache/html/*.html
